name: Generate Changelog RSTs

on:
  workflow_dispatch:
    inputs:
      codeql_branch:
        description: The branch in github/codeql from which to generate the CHANGELOG.md (codeql-cli-X.Y.Z)
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.codeql_branch }}

    - name: Configure git client and branch
      env:
        NEW_BRANCH_NAME: "spark-${{ inputs.codeql_branch }}-${{ github.run_id }}"
      run: |
        git show | head
        exit 1
        git fetch
        git switch -c "$NEW_BRANCH_NAME" origin/${{ inputs.codeql_branch }}

    - name: Install Spark's dependencies
      run: |
        sudo apt update
        sudo apt install libpcre16-3 libpcre3 libpcre3-dev libpcre32-3 libpcrecpp0v5

    - name: Download Spark
      working-directory: ${{ runner.temp }}
      env:
        # TODO: Use a PAT with sufficient permissions to github/codeql-spark.
        GH_TOKEN: ${{ secrets.CODEQL_SPARK_OWASP_TOKEN }}
      run: |
        # TODO: Change the -R argument to "github/codeql-spark".
        gh -R dsp-testing/mario-campos-docs-workflow release download v1.0.0
        unzip "spark-$RUNNER_OS-$RUNNER_ARCH.zip"

    - name: Generate ReStructuredText documentation from Markdown documentation
      working-directory: ${{ runner.temp }}
      env:
        # TODO: Use a PAT with sufficient permissions to github/codeql-owasp-top10-coverage.
        GH_TOKEN: ${{ secrets.CODEQL_SPARK_OWASP_TOKEN }}
      run: ./spark sitedocs "$GITHUB_WORKSPACE/docs/codeql/codeql-overview/codeql-changelog"

    - name: Check for changes to CodeQL docs
      id: changes
      run: |
        if git diff --quiet
        then
          echo 'No changes to CodeQL docs detected; nothing to commit.'
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Create PR
      if: steps.changes.outputs.changed == 'true'
      env:
        # TODO: Remove GH_DEBUG flag once `updatePullRequest` issue is fixed.
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

        git add .
        git commit -m 'update codeql documentation'
        git push -u origin HEAD

        gh pr create \
          --base '${{ github.event.inputs.codeql_branch }}' \
          --title '[Spark] Updated CodeQL microsite docs' \
          --assignee mario-campos \
          --reviewer mario-campos \
          --body-file <(cat <<EOF
        PR generated by actions to update the CodeQL docs.

        If you want to request a review by the Docs content team, please add the \`ready-for-doc-review\` label. This will add the PR to our review board and we'll aim to review it within the next 2 days. For more urgent help, ask in #docs-content.

        Opening this PR will trigger deployment of all changes to a preview site.
        - Wait for the preview site to deploy, you can see a link to details in the "check status" area of the PR.
        - Check the preview at the URL displayed when you click **Deployment** to view the deployment site.
        - Remember not to click any of the links in the header. Instead append \`/docs/\` to the URL to see the docs landing page.
        EOF
        )
